-- VIEWS
CREATE VIEW VW_ORDERS AS SELECT * FROM ORDERS

SELECT * FROM VW_ORDERS

-- VIEW FOR SOUTH REGION
CREATE VIEW SOUTH_ORDERS AS SELECT * FROM ORDERS WHERE Region = 'South'
SELECT * FROM SOUTH_ORDERS

--REFRENTIAL INTEGRITY CONSTRAINT

SELECT * FROM employee
SELECT * FROM dept

-- NOT POSSIBLE BECAUSE DEPT(DEP_ID) IS NOT PK
CREATE TABLE EMP (EMP_ID INT, EMP_NAME VARCHAR(10), 
DEP_ID INTEGER REFERENCES DEPT(DEP_ID))

ALTER TABLE DEPT ALTER COLUMN DEP_ID INT NOT NULL
ALTER TABLE DEPT ADD CONSTRAINT PRIMARY_KEY PRIMARY KEY (DEP_ID)

-- REF INTEGRITY
CREATE TABLE EMP (EMP_ID INT, EMP_NAME VARCHAR(10), 
DEP_ID INTEGER REFERENCES DEPT(DEP_ID))

INSERT INTO EMP VALUES (1, 'ANKIT', 100);
SELECT * FROM dept
SELECT * FROM EMP

-- FK CONTRAINT ERROR : DEP ID MISMATCH
INSERT INTO EMP VALUES (2, 'ANKITI', 500);

-- VALID
INSERT INTO EMP VALUES (2, 'ANKITI', NULL);

--INVALID
INSERT INTO dept VALUES (2, 'ANKITI', NULL);








